# Generated by Django 5.2.1 on 2025-05-11 06:30

from django.db import migrations
from django.contrib.auth import get_user_model

def create_sample_data(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Entry = apps.get_model("core", "Entry")
    User = get_user_model()

    # Sample categories
    income_categories = ["Salary", "Freelance", "Investments"]
    expense_categories = ["Groceries", "Rent", "Utilities", "Entertainment"]

    for name in income_categories:
        Category.objects.get_or_create(name=name, type="income")
    for name in expense_categories:
        Category.objects.get_or_create(name=name, type="expense")

    # Create test entries for the first user (if exists)
    user = User.objects.first()
    if user:
        salary_cat = Category.objects.get(name="Salary", type="income")
        groceries_cat = Category.objects.get(name="Groceries", type="expense")
        Entry.objects.create(
            user=user,
            amount=3000,
            category=salary_cat,
            date="2024-05-01",
            description="Monthly salary",
            amount_type="online",
            entry_type="income",
        )
        Entry.objects.create(
            user=user,
            amount=150,
            category=groceries_cat,
            date="2024-05-02",
            description="Weekly groceries",
            amount_type="cash",
            entry_type="expense",
        )

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sample_data),
    ]
