# Generated by Django 5.2.1 on 2025-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_category_options_alter_entry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="entry_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
