# Generated by Django 5.2.1 on 2025-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_category_entry_type_category_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='entry_type',
            field=models.CharField(
                choices=[('income', 'Income'), ('expense', 'Expense')],
                default='expense',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
