# Generated by Django 5.2.1 on 2025-05-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_category_entry_type_alter_category_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_salaried",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary_allowances",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly allowances like HRA, DA, etc.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary_currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary_day",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Day of the month when salary is received"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly deductions like tax, PF, etc.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("biweekly", "Bi-weekly"),
                    ("weekly", "Weekly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
