# Generated by Django 5.2.1 on 2025-05-12 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
