# Generated by Django 5.2.1 on 2025-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="currency_symbol",
            field=models.CharField(default="₹", max_length=5),
        ),
    ]
